baseURL = "http://www.bridportseakayak.co.uk/"
languageCode = "en-gb"
title = "Bridport Sea Kayak"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "seakayak"


#[menu]
# [[menu.navbar]]
#        identifier = "risk"
#        name = "Risk Assessment"
#        weight = 9
